'use client';

import { useState, useEffect, useMemo } from 'react';
import Link from 'next/link';
import ChartTooltip, { useTooltipState } from '@/components/shared/ChartTooltip';
import ChartContainer from '@/components/shared/ChartContainer';
import {
  Senti4SDDonut,
  Senti4SDDirectComparison,
  Senti4SDComplexity,
  Senti4SDHeatmap,
  Senti4SDCodeImpact,
  Senti4SDRelation,
} from '@/components/prototype/Senti4SDCharts';
import type { Turn } from '@/lib/types';

export default function Senti4SDPrototypePage() {
  const [turns, setTurns] = useState<Turn[]>([]);
  const [loading, setLoading] = useState(true);
  const tooltipData = useTooltipState();

  useEffect(() => {
    fetch('/data/senti4sd/processed_turns.json')
      .then(res => res.json())
      .then(data => {
        setTurns(data);
        setLoading(false);
      })
      .catch(err => {
        console.error('Failed to load Senti4SD turns data:', err);
        setLoading(false);
      });
  }, []);

  return (
    <div className="min-h-screen bg-white text-slate-800 font-sans">
      {/* Header */}
      <header className="px-6 py-3 bg-indigo-50/10 border-b border-indigo-100/50 backdrop-blur-md flex items-center justify-between sticky top-0 z-40">
        <div className="flex items-center gap-4">
          <Link href="/" className="text-sm text-indigo-600 hover:text-indigo-800 font-bold transition flex items-center gap-1.5">
            ← Back to Main Dashboard
          </Link>
          <span className="text-indigo-200">|</span>
          <h1 className="text-sm font-extrabold text-indigo-950">🧪 Senti4SD Sentiment Polarity Prototype</h1>
        </div>
        {!loading && (
          <span className="text-xs text-indigo-600 font-semibold bg-indigo-50/40 px-2.5 py-1 rounded-full border border-indigo-100/30">
            {turns.length.toLocaleString()} turns processed from DevGPT
          </span>
        )}
      </header>

      <main className="max-w-[1400px] mx-auto px-6 py-8 space-y-8">
        {/* Intro */}
        <div className="rounded-2xl border border-indigo-100 bg-indigo-50/15 p-5 shadow-sm space-y-3">
          <h2 className="text-xl font-extrabold text-indigo-950">Senti4SD Sentiment Polarity Prototype</h2>
          <p className="text-sm text-slate-600 leading-relaxed">
            Unlike fine-grained <strong>emotions</strong>, Senti4SD classifications are based on <strong>sentiment polarities</strong>. This prototype replicates the dashboard's analytics engine mapping developer and model actions using only 3 sentiment labels: <span className="text-emerald-600 font-bold">Positive</span>, <span className="text-slate-500 font-bold">Neutral</span>, and <span className="text-red-500 font-bold">Negative</span>.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 text-xs border-t border-indigo-100/40">
            <div className="space-y-1.5">
              <h4 className="font-bold text-indigo-950 uppercase tracking-wider">Naming Differences</h4>
              <ul className="list-disc pl-4 space-y-1 text-slate-600">
                <li><strong>Emotion Prototype (<code>/prototype</code>)</strong>: Mimics fine-grained raw emotional labels classified using models like GoEmotions (e.g., Frustration, Confusion, Satisfaction, Engagement).</li>
                <li><strong>Senti4SD Prototype (<code>/senti4sd-prototype</code>)</strong>: Classifies coarse-grained developer-specific sentiment polarity (Positive, Neutral, Negative).</li>
              </ul>
            </div>
            <div className="space-y-1.5">
              <h4 className="font-bold text-indigo-950 uppercase tracking-wider">File & Structure Differences</h4>
              <ul className="list-disc pl-4 space-y-1 text-slate-600">
                <li><strong>Emotion Data</strong>: Read from <code>public/data/processed_conversations.json</code>.</li>
                <li><strong>Senti4SD Data</strong>: Processed from raw DevGPT snapshots and written to a dedicated folder <code>public/data/senti4sd/processed_turns.json</code>.</li>
              </ul>
            </div>
          </div>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <div className="w-8 h-8 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin mr-3" />
            <span className="text-sm text-slate-500 font-medium animate-pulse">Running sentiment metrics on DevGPT snapshots...</span>
          </div>
        ) : (
          <div className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <ChartContainer title="Sentiment Label Distribution" subtitle="Distribution of positive, neutral, and negative labels generated by Senti4SD model">
                {({ width, height }) => <Senti4SDDonut data={turns} width={width} height={height} />}
              </ChartContainer>
              <ChartContainer title="Dev vs GPT — Sentiment Comparison" subtitle="Direct grouped sentiment counts classified for Developer vs GPT turns">
                {({ width, height }) => <Senti4SDDirectComparison data={turns} width={width} height={height} />}
              </ChartContainer>
            </div>

            <ChartContainer title="Developer Sentiment vs Prompt Complexity" subtitle="Developer sentiment distribution across Low / Medium / High prompt complexity levels">
              {({ width, height }) => <Senti4SDComplexity data={turns} width={width} height={height} />}
            </ChartContainer>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <ChartContainer title="Dev→GPT Sentiment Transition" subtitle="Turn-pair heatmap: which GPT response sentiment follows each developer sentiment state">
                {({ width, height }) => <Senti4SDHeatmap data={turns} width={width} height={height} />}
              </ChartContainer>
              <ChartContainer title="Code Context — AI Tone Impact" subtitle="GPT sentiment response splits grouped by code block presence">
                {({ width, height }) => <Senti4SDCodeImpact data={turns} width={width} height={height} />}
              </ChartContainer>
            </div>

            <ChartContainer title="Prompt Length vs Sentiment Polarity" subtitle="Developer turns plotted by prompt word count (X) against VADER compound polarity (Y)">
              {({ width, height }) => <Senti4SDRelation data={turns} width={width} height={height} />}
            </ChartContainer>
          </div>
        )}
      </main>

      <ChartTooltip data={tooltipData} />
    </div>
  );
}
